### PR TITLE
New pattern templates

### PR DESCRIPTION
**Pull request by aimorris**

### CODE REVIEW

**Comment by aimorris** [comment]
I'm unsure why, but `weekender`, `scholar`, and `washing-machine` have been put under Muttering Moat on the site, even though they are not in the `muterring-moat` directory.

**Comment by aimorris** [comment]
@TroyTae If you want to just merge this now, I'll create a new PR when I decide to search for new ones.

**Comment by TroyTae** [comment]
Ummm what's that means?

**Comment by aimorris** [comment]
> Ummm what's that means?

Merge this pull request.
I'll create a new pull request when I decide to add more templates.

**Comment by aimorris** [comment]
I've changed the `.gitignore` to include the `docs/` folder, which is where all the built files are.

**Comment by TroyTae** [comment]
Please don't add `gitignore` because github page is published by `docs`.
And it seems some files of `docs` are still alive.

**Comment by aimorris** [comment]
@TroyTae done.

**Comment by TroyTae** [comment]
Thank you for your hard work!
But.. I'm sorry, our engine isn't support spaceship pattern yet.
I'll improve our engine as soon as possible.
And then I'll open this issue.

**Pull request closed without merging**
