### PR TITLE
feat: p58 toadsucker

### LINKED ISSUE #1413: feat: p58 toadsucker
Let's make this pattern:
image

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p58-toadsucker.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by BlueGhost12**
resolve #1413

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
Please upload only p58-toadsucker.json

**Comment by BlueGhost12** [comment]
@TroyTae should I do a new pull request?

**Comment by TroyTae** [comment]
@BlueGhost12 
It's up to you.
But in this case, I think creating new PR is easier way.

**Comment by BlueGhost12** [comment]
I'm closing this PR. Ill be requesting a new PR. Thanks

**Pull request closed without merging**
