### PR TITLE
Pattern can have its own colors

### LINKED ISSUE #723: feat: Pick color for each pattern
Hello! I see that there are only 3 used colors to every pattern (black for survive, white for dead, and grey for the background). I think that it would be a nice addition to let each contributor put his own colors to the pattern he creates, so that it be more beautiful!
So, if you approve it, can I start improving the program?😄

### PR DESCRIPTION
**Pull request by LoukasPap**
resolve #723
Everything is working perfect, but it keeps throwing an error that I can not fix. 😢 
image
This error happens 21 times, for all the deadcolor, survivecolor and backgroundcolor in index.tx (inside renderLife(...) ). But even though these error, the program somehow works.

### CODE REVIEW

**Comment by TroyTae** [comment]
If you seems my code is ok, I'll merge this.

**Comment by LoukasPap** [comment]
Oh I had forgot about that! Now the code is perfect 😄 
By the way, you can put on new issues, the contributors to add color to 1-2 patterns.

**Comment by TroyTae** [comment]
@LoukasPap 
Yes you're right!
But after reorganizing website, I'll add color picker in website.
With this feature people can change to every colors freely 🌈

**Comment by LoukasPap** [comment]
That would be nice! Something else, the issue #723 is still open. Will you make it complete?

**Comment by TroyTae** [comment]
@LoukasPap 
After merge this PR, the issue is closed automatically :)

**Pull request merged**
