### PR TITLE
feat: opentomino

### LINKED ISSUE #1447: feat: opentomino
Let's make this pattern:
image

I checked your list but didn't find this. So we can add this I guess

### PR DESCRIPTION
**Pull request by ramyashreeshetty**
resolve #1447

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
Please fix prettier test error
And you don't need to make a new PR
Just commit your branch

**Comment by ramyashreeshetty** [comment]
there are no errors when i m testing over here

**Comment by TroyTae** [comment]
You mean CI result is wrong?

**Comment by ramyashreeshetty** [comment]
the thing is when i test it, i get prettier error and i m fixing it before committing. So i don't understand why am i getting this error?

**Comment by TroyTae** [comment]
Are there no changes when you run `npm run fix`?

**Comment by ramyashreeshetty** [comment]
there are. it gets fixed.

**Comment by TroyTae** [comment]
There are some formatting error so I fix it and commit at here(509740b)
Thank you for your contribution

**Pull request closed without merging**
