### PR TITLE
Feat: Octagon 2

### LINKED ISSUE #1321: feat: Octagon 2
Let's make this pattern:
image

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/octagon-2.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by Patea4**
resolve #1321

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
Please run `npm run fix:prettier`

**Comment by Patea4** [comment]
I Couldn't get it to work before, but now I think it is fine

**Review by TroyTae — APPROVED** [review]
LGTM
Thank you for your contribution :)

**Comment by Patea4** [comment]
Hey, could you add the hacktober tag to the pr?

**Pull request merged**
