### PR TITLE
feat: Odd keys

### LINKED ISSUE #1323: feat: Odd keys
Let's make this pattern:
image

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/odd-keys.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by preethi900**
1.resolved #1323 

2.Modfied odd-keys.json file for the mentioned pattern.

### CODE REVIEW

**Comment by MoulinLouis** [comment]
@preethi900 you have one comma that is not needed in your code

**Comment by preethi900** [comment]
@MoulinLouis  I will be fixing it.

**Comment by preethi900** [comment]
> @preethi900 you have one comma that is not needed in your code

Fixed it!!!

**Review by TroyTae — APPROVED** [review]
LGTM
Thank you for your contribution :)

**Comment by preethi900** [comment]
if u don't mind can u add the "hacktoberfest-accepted" to the approved PR ??It will help me count towards the Hacktoberfest challenge.

**Pull request merged**
