### PR TITLE
Add playground page

### LINKED ISSUE #756: feat: playground page
Requirement:
- This page needs three buttons (start / stop / reset)
  1. start => executive method `startLife`
  2. stop => executive method `stopLife`
  3. reset => reset to the pattern which sets first
- Pattern can handle with click (Like this: https://lukestorry.github.io/bool-array-filler/)
- Pattern's size can customize with two input (one text input for columns, one text input for rows)

### PR DESCRIPTION
**Pull request by LoukasPap**
resolve #756
We managed to insert the right rules, but we add only two of the buttons you asked, because we face some difficult problems. 😢 
**StartLife** button is working, but it must be pressed 2 times to start the loop.
**ClearLife** button is working, by reloading the page.
As for the **StopLife** button, we can not manage to create it. We have tried lots of things with Preact but none of them worked out.
If you have any idea on how to solve these problems, we are still available to fix it. But, feel free to assign the rest of this issue to someone else. He can continue from were we leave it off. But if it is easy, first accept our pull request, and then recreate the issue 😄
But in any case, with a little help we can finish the issue.

### CODE REVIEW

**Comment by TroyTae** [comment]
@LoukasPap 
Thank you for your hard effort!
Can you remove built files in `docs`?
I wanna focus code that you write :)

**Comment by LoukasPap** [comment]
> 
> 
> @LoukasPap @DinosXa
> Thank you for your hard effort!
> Can you remove built files in `docs`?
> I wanna focus on reading only the code you write :)

I have not fully understand what you mean. Do you want us to remove playground.html from the docs file?

**Comment by DinosXa** [comment]
@TroyTae  
Screenshot 2020-06-09 at 14 09 32

Would you be able to clarify what we should delete ?

**Comment by TroyTae** [comment]
image
Please delete these files.
These files are just  output of webpack build process.

**Comment by DinosXa** [comment]
@TroyTae we just deleted the files in docs as requested.

**Pull request merged**
