### PR TITLE
feat: Figure eight on Beluchenko's p13

### LINKED ISSUE #1313: feat: Figure eight on Beluchenko's p13
Let's make this pattern:
93170837-f0618500-f762-11ea-9357-bd1621eec829

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/figure-eight-on-beluchenkos-p13.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by tomasloksa**
resolve #1313 

Had to add one empty line on the left and top, because the pattern didn't fit.

### CODE REVIEW

**Comment by tomasloksa** [comment]
Also.. Could you please add the "hacktoberfest" topic to this repo? Everywhere it says, that PRs to any public repo count, but apparently, they don't...

**Review by TroyTae — APPROVED** [review]
Don't worry hacktoberfest will count every PRs of public repos.
```
Pull requests can be made in any GitHub-hosted repositories/projects. 
As long as the project is public and GitHub-hosted, your pull requests will count toward your participation.
```
I guess they need some times to sync your github data.
Anyway LGTM, thank you for your contribution :)

**Comment by tomasloksa** [comment]
@TroyTae Hey, hope you won't mind if i mention you here. I also read the rules and think that this PR should count, but apparently it doesn't. Could you, please, do any of this?
image

**Comment by TroyTae** [comment]
@tomasloksa I added the label. Good luck!

**Pull request merged**
