### PR TITLE
feat: Lei

### LINKED ISSUE #1240: feat: Lei
Let's make this pattern:
image

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/lei.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by DennisBoanini**
resolve #1240

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
image

**Comment by DennisBoanini** [comment]
> 
> 
> image

sorry @TroyTae but I don't understand your comment

**Comment by DennisBoanini** [comment]
I think that I have understand, I pushed the changes

**Review by TroyTae — APPROVED** [review]
LGTM

**Pull request merged**
