### PR TITLE
feat: Newshuttle

### LINKED ISSUE #1145: feat: Newshuttle
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/shuttle/newshuttle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

### PR DESCRIPTION
**Pull request by okdd08**
resolve #1145

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
image

**Review by TroyTae — CHANGES_REQUESTED** [review]
Hmm I think there are more wrong point.
Because oscillator patterns show same loop.
Would you please check back overall?
Now the life is dead after 70~80 generations.

**Comment by okdd08** [comment]
okay, i'll check that

**Review by TroyTae — APPROVED** [review]
👍

**Pull request merged**
