### PR TITLE
Almosymmetric

### LINKED ISSUE #674: feat: Almosymmetric
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/almosymmetric.ts

### PR DESCRIPTION
**Pull request by CAMYR71**
resolve #674

### CODE REVIEW

**Comment by CAMYR71** [comment]
Apologies for missing this.  How can I provide lint status.  When I run lint against all the code or the specific file, I get no output.  Apologies if this is a basic question.  Just learning to use lint

**Comment by CAMYR71** [comment]
Looking at the pull request again.  Looks like I messed up.  I updated more files than I should have.  I thought I had only requested almosymmetric.ts . You can reject this.  And I can do it again.

**Comment by TroyTae** [comment]
> Apologies for missing this. How can I provide lint status. When I run lint against all the code or the specific file, I get no output. Apologies if this is a basic question. Just learning to use lint

If there is no lint error, there is no output.
That means you got this work perfectly!
So don't apologies :)

**Comment by TroyTae** [comment]
> Looking at the pull request again. Looks like I messed up. I updated more files than I should have. I thought I had only requested almosymmetric.ts . You can reject this. And I can do it again.

It looks some commits are conflicted with master branch.
I'll fix this.
Thank you for your contribution 👍

**Comment by TroyTae** [comment]
moved to #682

**Pull request closed without merging**
