### PR TITLE
feat: 134P25

### LINKED ISSUE #714: feat: 134P25
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/134P25.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

### PR DESCRIPTION
**Pull request by LoukasPap**
resolve #714

### CODE REVIEW

**Comment by LoukasPap** [comment]
Do you mean to pull the newest changes, and then I do a new new pull request? If so, I will do.

**Comment by TroyTae** [comment]
`This branch is out-of-date with the base branch`
I can see this message and I think branch base make some conflicts.
So I hope you like this:
1. delete your forked repo (https://github.com/LoukasPap/game-of-life(
2. fork this repo again
3. copy and paste your code in this PR (only [134P25.ts](https://github.com/TroyTae/game-of-life/pull/720/files#diff-7954c0df12d1d109c72db87dc67b86b5))
4. create new PR
5. And I'll close this PR, and I'll approve and merge new PR

**Comment by LoukasPap** [comment]
image

If I update my branch, will the problem be solved? Or the only way is to delete the forked repo, and follow the other steps?

**Comment by TroyTae** [comment]
@LoukasPap 
I cannot sure, because I cannot see that button.
Can you click that button?
If the button's behavior can solve this problem we can merge this PR!
If not, please follow above guide please 😢

**Comment by TroyTae** [comment]
@LoukasPap 
Hmmm the message is still alive.
Please make a new PR 😭

**Comment by LoukasPap** [comment]
I will make a new RP, with the ability to change colors for each pattern :)

**Pull request closed without merging**
