### PR TITLE
Different color for each pattern solved

### LINKED ISSUE #714: feat: 134P25
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/134P25.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

### PR DESCRIPTION
**Pull request by LoukasPap**
resolve #714 & #723 
Added to each pattern's file, the option to put color for **DEAD_COLOR**, **SURVIVE_COLOR** and **BACKGROUND_COLOR**. These parameters are taken from `renderLife` method, then from `startlife` method and then from `clear` & `drawDots` methods, where the patterns are getting painted. If any color of the 3 is null ( example: DEAD_COLOR = '' ), then they take a default color from constants.ts.
In have already filled some patterns with colors, and it is great! 
New issues could be like a combination, of making a new pattern, and filling color's field of 2 other patterns. 😄

### CODE REVIEW

**Comment by TroyTae** [comment]
And I hope you separate two PR for #714 & #723.
In the current state, the commit records for two issues will push to mater branch by a single squash commit.

**Comment by LoukasPap** [comment]
So you mean, that each pattern inherits a class that has 3 `const` variables? If you explain it a little more, I will work on it. I'm just a little confused with what you mean.

**Comment by TroyTae** [comment]
@LoukasPap 
I thought to write like this:
```
class ColorGameOfLifeEngine extends GameOfLifeEngine {
   public backgroundColor: string;
   ~~~
}
```

**Comment by TroyTae** [comment]
@LoukasPap 
Umm if you use discord, I'll explain this more detail.

**Comment by LoukasPap** [comment]
I just downloaded it. My name is **loukaspap**.

**Comment by TroyTae** [comment]
@LoukasPap 
After installing, please adding me in your friends list.
I cannot find you, because I don't know your number tag

**Comment by LoukasPap** [comment]
loukaspap#0290 is my username

**Comment by TroyTae** [comment]
@LoukasPap 
I delete comments about our discord id for privacy :)

**Pull request closed without merging**
