### PR TITLE
feat: Fumarole on Rob's p16

### LINKED ISSUE #1181: feat: Fumarole on Rob's p16
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/fumarole-on-robs-p16.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

### PR DESCRIPTION
**Pull request by apoorv-tech**
resolve #1181

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
Please work at `src/life/oscillator/fumarole-on-robs-p16.json`, not `src/life/oscillator/blonker.json`

**Comment by premkiran7** [comment]
SInce @apoorv-tech has submitted a PR, I guess this task is done then @TroyTae?

**Comment by TroyTae** [comment]
@premkiran7 Yeah it seems @apoorv-tech missed your comment.
This task is ended, can you check out the other issue??

**Comment by TroyTae** [comment]
merged 93a269d941efb2c122cfd7a8aa1a445bb6205e48

**Pull request closed without merging**
