### PR TITLE
feat: Phoenix 1 

### LINKED ISSUE #1390: feat: Phoenix 1
Let's make this pattern:
image

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/phoenix/phoenix-1.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

### PR DESCRIPTION
**Pull request by tirlochanarora16**
resolve #1390

### CODE REVIEW

**Review by TroyTae — CHANGES_REQUESTED** [review]
Please run this command: `npm run fix:prettier`

**Review by tirlochanarora16 — COMMENTED** [review]
I just made these changes

**Review by TroyTae — APPROVED** [review]
LGTM
Thank you for your contribution :)

**Comment by tirlochanarora16** [comment]
Thank you for the opportunity! 😊

**Pull request merged**
