### PR TITLE
feat: Merzenich's p18

### LINKED ISSUE #1124: feat: Merzenich's p18
Let's make this pattern:
image

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/merzenichs-p18.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

### PR DESCRIPTION
**Pull request by irzakamran**
resolve #1124

### CODE REVIEW

**Comment by irzakamran** [comment]
i hope it was correct I used the boolarray filler to visualize as run npm start won't run on my macbook as showed a lot of errors.

**Comment by irzakamran** [comment]
How can i fix this failed test? Any help would be much appreciated as I am a beginner.

**Review by TroyTae — CHANGES_REQUESTED** [review]
There is a prettier error.
Please run this command: `npm run fix:prettier`

**Comment by irzakamran** [comment]
Hi @TroyTae thanks for replying. I ran this command and it did not work, the issue still persists. I manually used prettier (from command palette) to fix the prebuild.js file as well as the merzenichs-p18.json file but that was also to no avail. 
Screen Shot 2020-09-11 at 12 54 25 PM
Screen Shot 2020-09-11 at 12 54 18 PM

**Review by TroyTae — APPROVED** [review]
Hmmm I don't know specific reason, but I can run command.
And I push the code. Thank you for your contribution!

**Comment by irzakamran** [comment]
Great, thanks!

**Pull request merged**
